// MLCad v1.0 — Interface bilingue FR/EN
(function(){
  var lang='fr';
  var T={
    fr:{cadastre:'CADASTRE NUMÉRIQUE',tagline:'Plateforme numérique de consultation parcellaire',search:'Rechercher une parcelle (TF, lot, localité...)',layers:'Couches',coords:'Coordonnées',print:'Imprimer',guide:'Guide',about:'À propos',layerTitle:'Couches et fonds de plan',parcel:'Parcellaire',always:'Couche toujours visible',housing:'Habitation',green:'Espace vert',facility:'Équipement collectif',basemaps:'Fonds de plan',aboutTitle:'À propos de MLCad',about1:'MLCad est une plateforme numérique de consultation parcellaire permettant de visualiser, rechercher et consulter des informations cadastrales et foncières.',about2:'Elle facilite l’accès aux données parcellaires, la localisation des lots, la consultation des attributs et l’édition de fiches parcellaires.',legal:'Les informations affichées sont fournies à titre indicatif. Toute utilisation juridique doit se référer aux documents officiels délivrés par l’administration compétente.',developed:'Développé par François Sadio DANIOKO',profession:'Géographe-Aménagiste',guideTitle:'Guide d’utilisation',zoom:'Zoom :',zoomText:' + et – pour agrandir ou réduire la carte.',loc:'Géolocalisation :',locText:' Centrer la carte sur votre position.',measure:'Mesurer :',measureText:' Mesurer distances et surfaces.',find:'Recherche :',findText:' Retrouver un titre foncier avec son numéro.',legend:'Légende :',legendText:' Changer le fond de carte.',coordFind:'Recherche par coordonnées :',coordText:' Localiser un point à partir de ses coordonnées.',close:'Fermer',coordTitle:'Recherche par coordonnées',locate:'Localiser'},
    en:{cadastre:'DIGITAL CADASTRE',tagline:'Digital platform for parcel consultation',search:'Search a parcel (TF, lot, locality...)',layers:'Layers',coords:'Coordinates',print:'Print',guide:'Guide',about:'About',layerTitle:'Layers and basemaps',parcel:'Parcels',always:'Layer always visible',housing:'Residential',green:'Green space',facility:'Community facility',basemaps:'Basemaps',aboutTitle:'About MLCad',about1:'MLCad is a digital parcel consultation platform for viewing, searching and consulting cadastral and land information.',about2:'It facilitates access to parcel data, lot location, attribute consultation and the generation of parcel sheets.',legal:'The information displayed is provided for indicative purposes only. Any legal use must refer to official documents issued by the competent authority.',developed:'Developed by François Sadio DANIOKO',profession:'Geographer & Spatial Planner',guideTitle:'User guide',zoom:'Zoom:',zoomText:' use + and – to zoom in or out.',loc:'Geolocation:',locText:' center the map on your position.',measure:'Measure:',measureText:' measure distances and areas.',find:'Search:',findText:' find a land title by its number.',legend:'Legend:',legendText:' change the basemap.',coordFind:'Coordinate search:',coordText:' locate a point from its coordinates.',close:'Close',coordTitle:'Coordinate search',locate:'Locate'}
  };
  function txt(sel,v){var e=document.querySelector(sel);if(e)e.textContent=v;}
  function apply(l){lang=l==='en'?'en':'fr';var t=T[lang];document.documentElement.lang=lang;try{localStorage.setItem('mlcad-lang',lang);}catch(e){}
    txt('.auacad-brand-text strong',t.cadastre);txt('.auacad-brand-text span',t.tagline);
    var si=document.getElementById('auacad-header-search');if(si){si.placeholder=t.search;si.setAttribute('aria-label',t.search);}
    txt('#auacad-layers-btn span',t.layers);txt('#auacad-coord-btn span',t.coords);txt('#auacad-print-btn span',t.print);txt('#auacad-about-btn span',t.guide);txt('#auacad-readme-btn span',t.about);
    txt('#mlcad-layer-panel .mlcad-panel-title span',t.layerTitle);var sec=document.querySelectorAll('#mlcad-layer-panel .mlcad-section-title');if(sec[0])sec[0].textContent=t.parcel;if(sec[1])sec[1].textContent=t.basemaps;txt('#mlcad-layer-panel .mlcad-fixed-note',t.always);var lr=document.querySelectorAll('#mlcad-layer-panel .mlcad-legend-row span');if(lr[0])lr[0].textContent=t.housing;if(lr[1])lr[1].textContent=t.green;if(lr[2])lr[2].textContent=t.facility;
    var ap=document.getElementById('mlcad-about-panel');if(ap){txt('#mlcad-about-panel .mlcad-panel-title span',t.aboutTitle);var ps=ap.querySelectorAll('.mlcad-about-content p');if(ps[0])ps[0].innerHTML='<strong>MLCad</strong> '+t.about1.replace(/^MLCad\s*/,'');if(ps[1])ps[1].textContent=t.about2;if(ps[2])ps[2].textContent=t.legal;if(ps[3])ps[3].innerHTML='<strong>MLCad — Version 1.0</strong><br><br><strong>'+t.developed+'</strong><br><span>'+t.profession+'</span><br><a href="mailto:daniokof7@gmail.com" style="color:#096daf;text-decoration:none">daniokof7@gmail.com</a>';}
    var g=document.getElementById('map-info-box');if(g){var h=g.querySelector('h3');if(h)h.textContent=t.guideTitle;var p=g.querySelectorAll('p');var a=[[t.zoom,t.zoomText],[t.loc,t.locText],[t.measure,t.measureText],[t.find,t.findText],[t.legend,t.legendText],[t.coordFind,t.coordText]];for(var i=0;i<p.length&&i<a.length;i++){var icon=p[i].querySelector('.guide-icon');p[i].innerHTML=(icon?icon.outerHTML:'')+'<b>'+a[i][0]+'</b>'+a[i][1];}txt('#close-info',t.close);}
    txt('#coord-search-box h3',t.coordTitle);txt('#coord-search-btn',t.locate);txt('#coord-close-btn',t.close);
    var b=document.getElementById('mlcad-lang-btn');if(b)b.innerHTML=lang==='fr'?'<strong>FR</strong><span> | EN</span>':'<span>FR | </span><strong>EN</strong>';
  }
  function install(){if(!document.getElementById('map-title')||!document.getElementById('auacad-readme-btn')){setTimeout(install,150);return;}if(!document.getElementById('mlcad-lang-btn')){var actions=document.querySelector('.auacad-actions');if(actions){var b=document.createElement('button');b.type='button';b.id='mlcad-lang-btn';b.title='Français / English';b.setAttribute('aria-label','Français / English');b.style.cssText='min-width:54px;padding:0 8px;justify-content:center';b.onclick=function(){apply(lang==='fr'?'en':'fr');};actions.appendChild(b);}}
    var saved='fr';try{saved=localStorage.getItem('mlcad-lang')||'fr';}catch(e){}apply(saved);
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();